version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8012:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8011:80"
    depends_on:
      - flask_app